server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saga_payment
    username: root
    password: example
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update
      show-sql: true